/**
 * ======================================
 * SERVICE ENUM
 * ======================================
 * Fixed service keys
 */

const SERVICE_ENUM = {
  // Hair
  NANO_PLACENTA: "NANO_PLACENTA",
  BOTOX: "BOTOX",
  HAIR_FALL_TREATMENT_SPA: "HAIR_FALL_TREATMENT_SPA",
  ANTI_DANDRUFF_SPA: "ANTI_DANDRUFF_SPA",
  HAIR_PATCHES: "HAIR_PATCHES",
  HAIR_WIG: "HAIR_WIG",
  HAIR_EXTENSION_LADY: "HAIR_EXTENSION_LADY",
  HAIRCUT: "HAIRCUT",
  HAIR_COLOR: "HAIR_COLOR",
  HAIR_SPA: "HAIR_SPA",
  KERATIN_SMOOTHENING: "KERATIN_SMOOTHENING",

  // Makeup
  HALDI_MAKEUP: "HALDI_MAKEUP",
  GLAM_MAKEUP: "GLAM_MAKEUP",

  // Skin
  HYDRA_FACIAL: "HYDRA_FACIAL",
  KOREAN_GLASS_FACIAL: "KOREAN_GLASS_FACIAL",
  ANTI_TAN_FACIAL: "ANTI_TAN_FACIAL",
  GLOWING_FACIAL: "GLOWING_FACIAL",
  INSTANT_GLOW_FACIAL: "INSTANT_GLOW_FACIAL",
  HYDRATION_FACIAL: "HYDRATION_FACIAL",
  PIGMENTATION_TREATMENT: "PIGMENTATION_TREATMENT",

  // Body
  BODY_POLISHING: "BODY_POLISHING",
  FULL_BODY_WAXING: "FULL_BODY_WAXING",
  HALF_BODY_WAXING: "HALF_BODY_WAXING",
  MANICURE: "MANICURE",
  PEDICURE: "PEDICURE",
  DETAN_CLEANUP: "DETAN_CLEANUP",
  FACE_WAXING: "FACE_WAXING",

  // Nail & Beard
  NAIL_ART: "NAIL_ART",
  BEARD_COLOUR: "BEARD_COLOUR",
  SHAVING: "SHAVING",
  BEARD_TRIMMING: "BEARD_TRIMMING",
  BEARD_STYLING: "BEARD_STYLING",
};

export default SERVICE_ENUM;
